apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: default
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - image: ghcr.io/porplatakkom/devops-proxy:main
        name: proxy
